# Generated by Django 3.2.6 on 2021-08-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_type_id', models.AutoField(primary_key=True, serialize=True, unique=True)),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Виды топлива',
            },
        ),
        migrations.CreateModel(
            name='SignStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=True, unique=True)),
                ('status', models.CharField(max_length=100, verbose_name='статус заявки')),
            ],
            options={
                'verbose_name': 'Статус Заявки',
                'verbose_name_plural': 'Статусы Заявок',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=True, unique=True)),
                ('fuel_count', models.IntegerField(verbose_name='Количество топлива, л')),
                ('fuel_price', models.DecimalField(decimal_places=2, default=0, max_digits=29, verbose_name='Цена топлива')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_administration.fueltype', verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливо',
            },
        ),
        migrations.CreateModel(
            name='ClientSign',
            fields=[
                ('sign_code', models.IntegerField(auto_created=True, default=0, unique=True, verbose_name='Код заявки')),
                ('sign_id', models.AutoField(primary_key=True, serialize=True, unique=True)),
                ('first_last_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('source_type', models.CharField(max_length=10, verbose_name='Источник заявки')),
                ('client_id', models.CharField(max_length=50, verbose_name='Айди клиента(в боте)')),
                ('sign_date', models.DateTimeField(verbose_name='Дата заявки')),
                ('client_phone_number', models.IntegerField(default=0, verbose_name='Номер телефона клиента')),
                ('screenshot_link', models.CharField(max_length=100, verbose_name='Скриншот оплаты')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_administration.fuel', verbose_name='Топливо')),
                ('sign_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_administration.signstatus', verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
            },
        ),
    ]
